version: 2.1
orbs:
  node: circleci/node@3
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: lts
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Lint
          command: npm run lint
workflows:
  build-and-test:
    jobs:
      - build-and-test
