version: 2.1

aliases:
  - &runner
    executor:
      name: node/default
      tag: << parameters.node-version >>
  - &size
    resource_class: small
  - &params
    parameters:
      node-version:
        type: string

orbs:
  node: circleci/node@5

jobs:
  lint:
    <<: *runner
    <<: *size
    <<: *params
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-v1-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
            - node-modules-v1-{{ arch }}-{{ .Branch }}
            - node-modules-v1
      - run: npm i
      - save_cache:
          key: node-modules-v1-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run lint

workflows:
  build:
    jobs:
      - lint:
          node-version: lts
